AWSTemplateFormatVersion: "2010-09-09"
Description: Employee Match Game
Parameters:
  FQDN:
    Description: The domain name for the origin
    Type: String
    Default: match.thebeef.io
  CloudfrontDNSPrefix:
    Type: String
    Default: cloudfront
  LoggingBucketName:
    Description: The bucket to write CloudFront logs to
    Type: String
    Default: thebeef.io-corporate-logging
  LoggingPrefix:
    Description: The key prefix to write CloudFront logs to
    Type: String
    Default: match
Resources:
  MainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref FQDN
      ValidationMethod: DNS
  FQDNRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue TheBeefIoHostedZone
      Comment: Cloudfront origin for the site
      Name: !Ref FQDN
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 #CloudFront's HostedZone
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Sub "${FQDN}"
        Comment: !Sub "${FQDN} CloudFront"
        DefaultCacheBehavior:
          AllowedMethods:  ["HEAD", "GET", "OPTIONS" ]
          TargetOriginId: WebsiteOrigin
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        IPV6Enabled: true
        Logging:
          Bucket: !Sub "${LoggingBucketName}.s3.amazonaws.com"
          Prefix: !Sub "${LoggingPrefix}"
        Origins:
          - Id: WebsiteOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !Sub "${MainBucket}.s3-website-${AWS::Region}.amazonaws.com"
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref MainCertificate
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
      Tags:
      - Key: Name
        Value: !Sub ${FQDN}-cloudfront
  MainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref FQDN
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
      - Key: Name
        Value: !Ref FQDN
  MainBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref MainBucket
      PolicyDocument: 
        Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: arn:aws:s3:::match.thebeef.io/*
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LoggingBucketName
      Tags:
      - Key: Name
        Value: !Ref LoggingBucketName